# Generated by Django 2.1.7 on 2019-03-24 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=50)),
                ('tm_stmp', models.DateTimeField()),
                ('ip_t', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('time_commi', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('school', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpt', models.CharField(blank=True, default='', max_length=30)),
                ('pstn', models.CharField(blank=True, default='', max_length=20)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Published_Question',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('tm_stmp', models.DateTimeField()),
                ('seconds_limit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ans_1', models.TextField()),
                ('ans_2', models.TextField()),
                ('ans_3', models.TextField()),
                ('ans_4', models.TextField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField()),
                ('level', models.IntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('bd_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_class', models.ManyToManyField(to='login.Class')),
                ('s_course', models.ManyToManyField(to='login.Course')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('st_time', models.TimeField()),
                ('en_time', models.TimeField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Class')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_Period',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('st_date', models.DateField()),
                ('en_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('credits', models.PositiveIntegerField()),
                ('image', models.CharField(default='default.jpg', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Unit'),
        ),
        migrations.AddField(
            model_name='published_question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Question'),
        ),
        migrations.AddField(
            model_name='class',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_id', to='login.Employee'),
        ),
        migrations.AddField(
            model_name='class',
            name='t_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Teaching_Period'),
        ),
        migrations.AddField(
            model_name='class',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Unit'),
        ),
        migrations.AddField(
            model_name='answer',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='teach_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.Teaching_Day'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('text', 'staff_id')},
        ),
    ]
