# Generated by Django 2.1.7 on 2019-03-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaching_day',
            old_name='date',
            new_name='date_td',
        ),
    ]
