# Generated by Django 2.1.7 on 2019-03-18 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='l_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sha',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_id', to='login.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dpt',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pstn',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
