# Generated by Django 2.1.7 on 2019-03-25 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('time_commi', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=1)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_id', to='administrative.Employee')),
                ('t_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrative.Teaching_Period')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrative.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Published_Question',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tm_stmp', models.DateTimeField(auto_now_add=True)),
                ('seconds_limit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('ans_1', models.CharField(max_length=255)),
                ('ans_2', models.CharField(max_length=255)),
                ('ans_3', models.CharField(max_length=255)),
                ('ans_4', models.CharField(max_length=255)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrative.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_td', models.DateField()),
                ('st_time', models.TimeField()),
                ('en_time', models.TimeField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecturer.Class')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrative.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrative.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecturer.Topic'),
        ),
        migrations.AddField(
            model_name='published_question',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lecturer.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='teaching_day',
            unique_together={('c_id', 'date_td')},
        ),
    ]
